FROM oven/bun:1-debian

ARG USERNAME=mario

ENV NODE_ENV=development

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      ca-certificates \
      git \
      openssl \
      redis-server \
      sqlite3 \
      libsqlite3-dev \
    && usermod --login ${USERNAME} --move-home --home /home/${USERNAME} bun \
    && groupmod --new-name ${USERNAME} bun \
    && mkdir -p /home/${USERNAME}/.bun/install/cache /alp/api/node_modules /alp/api/data \
    && chown -R ${USERNAME}:${USERNAME} /home/${USERNAME} /alp/api \
    && rm -rf /var/lib/apt/lists/*

USER ${USERNAME}
WORKDIR /alp/api

CMD redis-server --daemonize yes --save "" --appendonly no --pidfile /tmp/redis.pid && bun run dev
